version: '2'
services:
  mocked-oauth-server:
    image: mocked-oauth-server:0.0-SNAPSHOT
    container_name: mocked-oauth-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - "8081:8081"
